# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# POSTGRESQL (NEON)
# =========================
spring.datasource.url=jdbc:postgresql://ep-steep-star-aqgymchf-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_aC0nzWSDk3RJ

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# GRAPHQL
# =========================
spring.graphql.graphiql.enabled=true

# =========================
# SMTP GMAIL
# =========================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=m21ce056@cenidet.tecnm.mx
smtp.password=ggbs yich nnpj wqxf

# =========================
# KAFKA AIVEN
# =========================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

spring.kafka.consumer.group-id=cart-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer