# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# POSTGRESQL (NEON)
# =========================
spring.datasource.url=jdbc:postgresql://ep-steep-star-aqgymchf-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_aC0nzWSDk3RJ

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# GRAPHQL
# =========================
spring.graphql.graphiql.enabled=true

# =========================
# SMTP GMAIL
# =========================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=m21ce056@cenidet.tecnm.mx
smtp.password=ggbs yich nnpj wqxf

# =========================
# KAFKA (DESHABILITADO PARA CLOUD RUN)
# =========================
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration